name: 'Argument Counter'
description: 'Count # of arguments passed in'
inputs:
  arguments-to-count: # input id
    description: 'arguments to count'
    required: true
    default: ''
outputs:
  arg-count:
    description: "Count of arguments passed in"
    value: ${{ steps.return-result.outputs.num-args }}
runs:
  using: "composite"
  steps:
    - name: Print arguments if any
      run: |
        echo Arguments: ${{ inputs.arguments-to-count }}.
      shell: bash
    - id: return-result
      run: |
        echo "num-args=`${{ github.action_path }}/count-args.sh ${{ inputs.arguments-to-count }}`" >> $GITHUB_OUTPUT
      shell: bash
      
  count-args:
      
    runs-on: ubuntu-latest
    
    steps: 
    - id: report-count
      uses: <your github userid>/arg-count-action@main
      with: 
        arguments-to-count: ${{ github.event.inputs.myValues }}
    - run: echo 
    - shell: bash
      run: |
        echo argument count is ${{ steps.report-count.outputs.arg-count }}  
